// Dados de cidades e patologias

List<String> cidades = [
  "Selecione",
  "Belem",
  "Ananindeua",
  "Abaetetuba",
  "Barcarena",
  "Castanhal",
  "maranhao",
  "Abel Figueiredo",
  "Acará",
  "Afuá",
  "Água Azul do Norte",
  "Alenquer",
  "Almeirim",
  "Altamira",
  "Anajás",
  "Anapu",
  "Augusto Corrêa",
  "Aurora do Pará",
  "Aveiro",
  "Bagre",
  "Baião",
  "Bannach",
  "Belterra",
  "Benevides",
  "Bom Jesus do Tocantins",
  "Bonito",
  "Bragança",
  "Brasil Novo",
  "Brejo Grande do Araguaia",
  "Breu Branco",
  "Breves",
  "Bujaru",
  "Cachoeira do Arari",
  "Cachoeira do Piriá",
  "Cametá",
  "Canaã dos Carajás",
  "Capanema",
  "Capitão Poço",
  "Chaves",
  "Colares",
  "Conceição do Araguaia",
  "Concórdia do Pará",
  "Cumaru do Norte",
  "Curionópolis",
  "Curralinho",
  "Curuá",
  "Curuçá",
  "Dom Eliseu",
  "Eldorado dos Carajás",
  "Faro",
  "Floresta do Araguaia",
  "Garrafão do Norte",
  "Goianésia do Pará",
  "Gurupá",
  "Igarapé-Açu",
  "Igarapé-Miri",
  "Inhangapi",
  "Ipixuna do Pará",
  "Irituia",
  "Itaituba",
  "Itupiranga",
  "Jacareacanga",
  "Jacundá",
  "Juruti",
  "Limoeiro do Ajuru",
  "Mãe do Rio",
  "Magalhães Barata",
  "Marabá",
  "Maracanã",
  "Marapanim",
  "Marituba",
  "Medicilândia",
  "Melgaço",
  "Mocajuba",
  "Moju",
  "Monte Alegre",
  "Muaná",
  "Nova Esperança do Piriá",
  "Nova Ipixuna",
  "Nova Timboteua",
  "Novo Progresso",
  "Novo Repartimento",
  "Óbidos",
  "Oeiras do Pará",
  "Oriximiná",
  "Ourém",
  "Ourilândia do Norte",
  "Pacajá",
  "Palestina do Pará",
  "Paragominas",
  "Parauapebas",
  "Pau D'Arco",
  "Peixe-Boi",
  "Piçarra",
  "Placas",
  "Ponta de Pedras",
  "Portel",
  "Porto de Moz",
  "Prainha",
  "Primavera",
  "Quatipuru",
  "Redenção",
  "Rio Maria",
  "Rondon do Pará",
  "Rurópolis",
  "Salinópolis",
  "Salvaterra",
  "Santa Bárbara do Pará",
  "Santa Cruz do Arari",
  "Santa Isabel do Pará",
  "Santa Luzia do Pará",
  "Santa Maria das Barreiras",
  "Santa Maria do Pará",
  "Santana do Araguaia",
  "Santarém",
  "Santarém Novo",
  "Santo Antônio do Tauá",
  "São Caetano de Odivelas",
  "São Domingos do Araguaia",
  "São Domingos do Capim",
  "São Félix do Xingu",
  "São Francisco do Pará",
  "São Geraldo do Araguaia",
  "São João da Ponta",
  "São João de Pirabas",
  "São João do Araguaia",
  "São Miguel do Guamá",
  "São Sebastião da Boa Vista",
  "Sapucaia",
  "Senador José Porfírio",
  "Soure",
  "Tailândia",
  "Terra Alta",
  "Terra Santa",
  "Tomé-Açu",
  "Tracuateua",
  "Trairão",
  "Tucumã",
  "Tucuruí",
  "Ulianópolis",
  "Uruará",
  "Vigia",
  "Viseu",
  "Vitória do Xingu",
  "Xinguara"
];

List<String> patologiasMaisVistas = [
  "Selecione",
  "Abuso de álcool ou drogas",
  "Acidentes vasculares cerebrais (AVC)",
  "Ataques de pânico",
  "Bolhas: Feridas nos pés",
  "Convulsões (em pessoas epilépticas ou com histórico de crises)",
  "Cortes ou lacerações graves (devido a acidentes ou multidões)",
  "Desidratação",
  "Desmaios: Perda de consciência",
  "Exaustão física",
  "Ferimentos leves (cortes, arranhões)",
  "Hipertensão (Pressão alta)",
  "Hipoglicemia (Queda de açúcar sem sangue)",
  "Hipotensão (Pressão baixa)",
  "Lesões por esforço repetitivo",
  "Problemas ortopédicos (Torções, fraturas ou dores musculares)",
  "Problemas respiratórios",
  "Reações alérgicas a picadas de insetos",
  "Traumas devido a quedas ou empurrões",
  "Outros"
];
